Träning från w3school

In [12]:
import pandas as pd


my_dataset= {
    'cars': ['volvo', 'fiat', 'BMW'], 
    'passings': [ 2, 5, 6]
}

my_var= pd.DataFrame(my_dataset)

print(my_var)
print('\n')
print(my_var.loc[[0,1]])

    cars  passings
0  volvo         2
1   fiat         5
2    BMW         6


    cars  passings
0  volvo         2
1   fiat         5

In [6]:
import pandas as pd
calories= {'calories': [3000, 4000, 5000, 4000], 'duration': [22, 55, 33, 77]}

df= pd.DataFrame(calories, index=['day1', 'day2', 'day3', 'day4'])


print(df)
print('\n')
print(df.loc[['day2']])

      calories  duration
day1      3000        22
day2      4000        55
day3      5000        33
day4      4000        77


      calories  duration
day2      4000        55

In [7]:
df= pd.read_csv('data.csv')

print(df)
df.loc[1]

        Datum      Produkt  Antal  Enhetspris  Totalbelopp
0  2024-01-15       Laptop      2       12000        24000
1  2024-01-16          Mus     10         250         2500
2  2024-01-17  Tangentbord      5         800         4000
3  2024-01-18        Skärm      3        3500        10500

Datum          2024-01-16
Produkt               Mus
Antal                  10
Enhetspris            250
Totalbelopp          2500
Name: 1, dtype: object

In [ ]:
df = pd.read_csv('data2.csv')
print(df.dtypes)
#print(df.to_string())
print(df.Maxpulse)
print(df['Maxpulse'])

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object
0      130
1      145
2      135
3      175
4      148
      ...
164    140
165    145
166    145
167    150
168    150
Name: Maxpulse, Length: 169, dtype: int64
0      130
1      145
2      135
3      175
4      148
      ...
164    140
165    145
166    145
167    150
168    150
Name: Maxpulse, Length: 169, dtype: int64

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [84]:
df = pd.read_json('data.json')

print(df.iloc[0]) #row first
#print(df.iloc[:, 0]) #column first : = everything
#print(df.iloc[:3, 0]) #column first :3 3 first  3 rows
#print(df.iloc[1:3, 0]) #column first 1:3 3 second and third rows 
#print(df.iloc[[1,2,3], 0]) 
df.loc[(df.Duration == 60) & (df.Maxpulse >= 140)]
df.loc[(df.Duration == 60) | (df.Maxpulse >= 140)]
df.loc[df.Maxpulse.isin([140, 137])]
df.loc[df.Calories.isnull()]
df.loc[df.Calories.notnull()]

indicies=[1,2,3,4,5]
cols=['Maxpulse', 'Duration']
df.loc[indicies, cols]

df

#print(df.to_string())
# print(df.head(10))
# print(df.tail(10))
# print(df.info())

Duration     60.0
Pulse       110.0
Maxpulse    130.0
Calories    409.1
Name: 0, dtype: float64

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [81]:
df = pd.read_csv('data.csv')
df.describe()
df.Enhetspris.mean()

df2=pd.read_json('data.json')
df2.Pulse.describe()
df2.Calories.unique()
df2.Duration.value_counts()
over_average= df2.Duration - df2.Duration.mean()
over_average.loc[over_average >= 1]
longest_duration= df2.loc[df2.Duration.idxmax()]
longest_duration

Duration     300.0
Pulse        108.0
Maxpulse     143.0
Calories    1500.2
Name: 69, dtype: float64

6.
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

In [92]:

# count_tropical= reviews.description.map(lambda desc: "tropical" in desc).sum()
# count_fruity= reviews.description.map(lambda desc: "fruity" in desc).sum()
# print(count_fruity)
# descriptor_counts = pd.Series([count_tropical, count_fruity], index= ['tropical', 'fruity'])

# print(descriptor_counts)


7.
We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [110]:



def set_pulse_over_140_good(row):
    if row.Pulse > 110:
        return 'Good job'
    else:
        return 'Bad'


hej= df2.apply(set_pulse_over_140_good, axis='columns')

#print(hej)

#df2.groupby('Maxpulse').Maxpulse.count()
df2.groupby('Maxpulse').Duration.min()

Maxpulse
100     15
101     60
103     45
107     20
108     30
110     90
112     20
113     60
115     60
118     60
119     45
120     30
121     60
122     60
123     60
124     45
125     45
126     45
127     30
128     30
129     45
130     20
131     30
132     45
133     30
134     45
135     60
136     20
137     30
138     45
139     15
140     45
141     45
143     45
144     45
145     60
146     45
147     60
148     45
149     45
150     60
151     60
152     45
153     60
156     20
157    120
160    210
162     20
167     30
168     20
169     45
170     30
171     20
172     20
175     30
182     30
184    210
Name: Duration, dtype: int64

In [113]:
df= pd.read_csv('wine.csv')
df.groupby(['country']).price.agg([len, min, max])

                          len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   NaN     NaN
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0